#define PROGRAMnumber 1
#define VARnumber 2
#define BEGINnumber 3
#define ENDnumber 4
#define ENDDOTnumber 5
#define INTEGERnumber 6
#define FORnumber 7
#define READnumber 8
#define WRITEnumber 9
#define TOnumber 10
#define DOnumber 11
#define SEMICOLONnumber 12
#define COLONnumber 13
#define COMMAnumber 14
#define COLEQUALnumber 15
#define PLUSnumber 16
#define MINUSnumber 17
#define ASTERISKnumber 18
#define DIVnumber 19
#define LEFTPARENTHESISnumber 20
#define RIGHTPARENTHESISnumber 21
#define IDnumber 22
#define INTnumber 23
